### ISSUE TITLE
"Plugin could not be activated because it triggered a fatal error."

### ISSUE THREAD

**Issue by bersbersbers** [Pierre-Lannoy/wp-apcu-manager#9]
After updating to 3.8.1, I was getting this:

```
An error of type E_ERROR was caused in line 12 of the file /data/.../wp-content/plugins/apcu-manager/includes/libraries/decalog-sdk/EventsLogger.php.
Error message: Uncaught Error: Undefined constant "DecaLog\DECALOG_VERSION" in /data/.../wp-content/plugins/apcu-manager/includes/libraries/decalog-sdk/EventsLogger.php:12
Stack trace:
#0 /data/.../wp-content/plugins/apcu-manager/includes/libraries/autoload.php(28): include_once()
#1 /data/.../wp-content/plugins/apcu-manager/includes/libraries/decalog-sdk/Engine.php(197): {closure}('DecaLog\\EventsL...')
#2 /data/.../wp-content/plugins/apcu-manager/apcu-manager.php(137): DecaLog\Engine::eventsLogger('apcu-manager')
#3 /data/.../wp-content/plugins/apcu-manager/apcu-manager.php(155): apcm_run()
#4 /data/.../wp-settings.php(517): include_once('/data/web/1/000...')
#5 /data/.../wp-config.php(28): require_once('/data/web/1/000...')
#6 /data/.../wp-load.php(50): require_once('/data/web/1/000...')
#7 /data/.../wp-admin/admin.php(34): require_once('/data/web/1/000...')
#8 /data/.../wp-admin/themes.php(10): require_once('/data/web/1/000...')
#9 {main}
  thrown
```

From recovery mode, I was able to disable the plugin - now it does not activate any longer.

**Comment by Pierre-Lannoy** [comment]
Hello @bersbersbers !
I am deeply, deeply sorry for what has just happened: a wrong development version has been pushed on the WordPress directory (due to an error on my part) and, consequently, deployed on your sites.
A new version is now available and should fix this issue.
Please, accept my sincere apologies.
Pierre

**Comment by bersbersbers** [comment]
No problem at all! Cost me 10 minutes to figure out and work around. 3.8.3 is working fine again. Thanks for the quick resolution 😃
